In [1]:
import numpy as np

In [2]:
arr = np.arange(1,100,2)
print('Odd array',arr)

Odd array [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [4]:
arr2 = arr.reshape(10,5)
print(arr2)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


In [11]:
print(arr2[3:7,1:4])
print(arr2[:,0::4])

[[33 35 37]
 [43 45 47]
 [53 55 57]
 [63 65 67]]
[[ 1  9]
 [11 19]
 [21 29]
 [31 39]
 [41 49]
 [51 59]
 [61 69]
 [71 79]
 [81 89]
 [91 99]]
