Jay Shree Ram***

In [6]:
print("Jay Shree Ram")

Jay Shree Ram


In [13]:
import numpy as np

In [23]:
print("2D Array:")

arr2D = np.array([[1,2,3,4,5],[3,4,4,5,6],[5,6,7,8,9]])
print(arr2D)
print("size = ",arr2D.size)
print("shape =",arr2D.shape)
print("transepose =",arr2D.transpose())
print("flatten=",arr2D.flatten())
print("raval=",arr2D.ravel())


2D Array:
[[1 2 3 4 5]
 [3 4 4 5 6]
 [5 6 7 8 9]]
size =  15
shape = (3, 5)
transepose = [[1 3 5]
 [2 4 6]
 [3 4 7]
 [4 5 8]
 [5 6 9]]
flatten= [1 2 3 4 5 3 4 4 5 6 5 6 7 8 9]
raval= [1 2 3 4 5 3 4 4 5 6 5 6 7 8 9]


-- *ravel():* Below is ravel which is faster than flatten and which is not create copy of original array if you make chanegs in ravel it reflect in original array also <br>
--*flatten():*Below is flatten which store copy of original array and it consumes memory for that also it is slower that ravel and if you make changes in flatten array not reflect in original array

In [24]:
arr = np.array([[1,2,3],[1,2,4]])

flatten = arr.flatten()
ravel = arr.ravel()

ravel[0]=45
flatten[0]=55

print("Original array=",arr)
print("flatten array=",flatten)
print("ravel array=",ravel)

Original array= [[45  2  3]
 [ 1  2  4]]
flatten array= [55  2  3  1  2  4]
ravel array= [45  2  3  1  2  4]
