In [1]:
import numpy as np

In [7]:
a = np.arange(21,41).reshape(5,4)
b = np.arange(1,21).reshape(5,4)

print(a)
print(b)

[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
c = np.subtract(a,b)
d =np.multiply(a,b)
print("Substration:\n",c,"\nMultiply:\n",d)

print("\nAddition:\n",np.add(a,b))

a*b
b = b.reshape(4,5)
a@b  #it is actual cross multiplication of two array i am rashape it because it need to (4,5)*(5,4)

In [35]:
print(a)
print("max by row=",a.max(axis=1))
a.min(axis=0)

[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]]
max by row= [24 28 32 36 40]


array([21, 22, 23, 24])

In [46]:
np.sqrt(a)

array([[4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262],
       [5.38516481, 5.47722558, 5.56776436, 5.65685425],
       [5.74456265, 5.83095189, 5.91607978, 6.        ],
       [6.08276253, 6.164414  , 6.244998  , 6.32455532]])

In [ ]:
np.mean(a,axis=1)

array([22.5, 26.5, 30.5, 34.5, 38.5])

In [ ]:
np.log(a)

array([[3.04452244, 3.09104245, 3.13549422, 3.17805383],
       [3.21887582, 3.25809654, 3.29583687, 3.33220451],
       [3.36729583, 3.40119738, 3.4339872 , 3.4657359 ],
       [3.49650756, 3.52636052, 3.55534806, 3.58351894],
       [3.61091791, 3.63758616, 3.66356165, 3.68887945]])

In [47]:
np.std(a,axis=0)

array([5.65685425, 5.65685425, 5.65685425, 5.65685425])